/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/Admin': RouteRecordInfo<'/admin/Admin', '/admin/Admin', Record<never, never>, Record<never, never>>,
    '/admin/Settings': RouteRecordInfo<'/admin/Settings', '/admin/Settings', Record<never, never>, Record<never, never>>,
    '/admin/TeacherAccount': RouteRecordInfo<'/admin/TeacherAccount', '/admin/TeacherAccount', Record<never, never>, Record<never, never>>,
    '/admin/TeacherList': RouteRecordInfo<'/admin/TeacherList', '/admin/TeacherList', Record<never, never>, Record<never, never>>,
    '/admin/TeachersPage': RouteRecordInfo<'/admin/TeachersPage', '/admin/TeachersPage', Record<never, never>, Record<never, never>>,
    '/admin/UserList': RouteRecordInfo<'/admin/UserList', '/admin/UserList', Record<never, never>, Record<never, never>>,
    '/home/DataEntry': RouteRecordInfo<'/home/DataEntry', '/home/DataEntry', Record<never, never>, Record<never, never>>,
    '/home/Home': RouteRecordInfo<'/home/Home', '/home/Home', Record<never, never>, Record<never, never>>,
    '/home/Profiles': RouteRecordInfo<'/home/Profiles', '/home/Profiles', Record<never, never>, Record<never, never>>,
    '/home/Records': RouteRecordInfo<'/home/Records', '/home/Records', Record<never, never>, Record<never, never>>,
    '/home/Tracking': RouteRecordInfo<'/home/Tracking', '/home/Tracking', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/Welcome': RouteRecordInfo<'/Welcome', '/Welcome', Record<never, never>, Record<never, never>>,
  }
}
